### ISSUE TITLE
Missing styling for QTableCornerButton ?

### ISSUE THREAD

**Issue by eleriaqueen** [adamerose/QStylish#1]
Hello your work looks amazing !
I've manually integrated both stylesheets in my C++ project structure to check them out, they seem to work well (Using Fusion Style for QApplication, then loading the qss files) though I noticed the QTableCornerButton is solid black with both themes.

![Sanctuary_dphzyfIwNv](https://user-images.githubusercontent.com/4411178/127565462-093d08c2-1f62-471a-82ef-96fb1899ce3d.png)

As a quick fix I added : 
`QTableCornerButton::section {
  background-color: #373a3f; }`
to the dark theme, and it seemed to do the trick.

![Sanctuary_hjmPEAs27U](https://user-images.githubusercontent.com/4411178/127565636-83c7096a-7692-4204-929f-19197e09e6e4.png)

I'm a beginner in Qt stylesheets, if the issue is caused by the fact I'm using the stylesheets in a C++ project then I'm sorry !

**Comment by adamerose** [comment]
Should be fixed in 0.1.4
